version: "3.9"

volumes:
  acme-challenge:
    driver: local

services:

  certbot:
    image: certbot/certbot
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt:rw
      - acme-challenge:/var/www/acme-challenge:rw
