version: "3.9"

networks:
  gitea:
    external: false

volumes:
  acme-challenge:
    driver: local

services:

  nginx:
    image: nginx:1.23.1-alpine
    container_name: nginx
    environment:
      - DOMAIN=${DOMAIN}
    restart: always
    depends_on:
      - "gitea"
    networks:
      - gitea
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./etc/nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro
      - acme-challenge:/var/www/acme-challenge:ro
    ports:
      - "80:80"
      - "443:443"

  gitea:
    image: gitea/gitea:1.17.4
    container_name: gitea
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
    restart: always
    networks:
      - gitea
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh:/data/git/.ssh:rw
      - ./data:/data:rw
    ports:
      - "127.0.0.1:2222:22"
